### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by Hypsilofodon** [m4dhouse/Wireguard-Vpn#11]
Unable to install on OpenATV 7.3 DM920 - getting the error -  * calculate_dependencies_for: Cannot satisfy the following dependencies for enigma2-plugin-extensions-wireguard-vpn: * 	wireguard-tools * 	wireguard-tools-bash-completion * 
Upgrading enigma2-plugin-extensions-wireguard-vpn from 8.4 to 9.3 on root.

When forcing installation without dependencies I am unable to connect to any server with getting error - Wireguard protocol miossing ! Check that WireGuard is installed in your image. Via Telnet : opkg install wireguard-tools

root@dm920:/tmp# opkg install wireguard-tools
Unknown package 'wireguard-tools'.
 * opkg_solver_install: Cannot install package wireguard-tools.

**Comment by Hypsilofodon** [comment]
Sorry, issue resolved :)

**Comment by m4dhouse** [comment]
Dm900/920 are not supported by WireGuard in Egami and OpenAtv images.

**Comment by Hypsilofodon** [comment]
> Dm900/920 are not supported by WireGuard in Egami and OpenAtv images.

Thank you @m4dhouse for your quick reply and sorry for the next question, but do you know which software/image is compatible with WireGuard?

**Comment by m4dhouse** [comment]
I do not know sorry.
