### ISSUE TITLE
Openatv 7.4 Wireguard 10.7 roaming dont work

### ISSUE THREAD

**Issue by nicon12** [m4dhouse/Wireguard-Vpn#13]
Hi when i have in AllowedIPs 0.0.0.0/0 or 0.0.0.0/1, 128.0.0.0/1 it works and every data goes complet through the tunel vpn, but if i would like to VPN tunel only for my LAN it isnt work. For example if i have in AllowedIPs only 192.168.0.0/24.

**Comment by m4dhouse** [comment]
This is a general problem of the box kernel, you must necessarily allow all the IPs on the network.

**Comment by techniker2103** [comment]
Hello, I have the same problem, which IP do I have to share in which network?

**Comment by m4dhouse** [comment]
> Hello, I have the same problem, which IP do I have to share in which network?

AllowedIps = 0.0.0.0/1,128.0.0.0/1
