### ISSUE TITLE
OpenATV crashes, as soon as you want to save or exit the plugin

### ISSUE THREAD

**Issue by DigitGram** [m4dhouse/Wireguard-Vpn#14]
OpenATV: v7.4
wireguard-vpn: 10.7 (installed from feed)

_Steps to reproduce:_

- saved my OWN config at /media/hdd/WgConfig/MyConfig.conf
- Config gets recognized by plugin
- My VPN server is at my same home network (tried to test it, if Plugin works)
- only default settings
- As soon as I hit red (close) or green (save) button within openend plugin, OpenATV crashes with bluescreen. See attached logfile.

Thanks for this great plugin. Hope to see a fix!

Kind regards,
$me

[20240807-225431-enigma2-crash.log](https://github.com/user-attachments/files/16534412/20240807-225431-enigma2-crash.log)

**Comment by DigitGram** [comment]
Narrowed it down.
If you enable "create a backup script", openATV will crash. Everything else works.

_Workaround_ so far:
Do NOT enable "create a backup script" (in german: "Erstellen eines Sicherungsskripts").

**Comment by m4dhouse** [comment]
Fixed on next version.
Thanks
