### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by vrondena** [m4dhouse/Wireguard-Vpn#15]
Hello, on my vuplus duo2 the installation of the mips 10.7 all file reports an error
conflicting requests,
 nothing provides wireguards tools needed by enigma2-plugins-extensions-wirwguard-vpn-mips-10.7 all 
solution .. do no ask to install

How can I solve it, thank you

**Comment by m4dhouse** [comment]
WireGuard requires a linux version greater than 3.10.
