### ISSUE TITLE
Trying to connect generates error ...

### ISSUE THREAD

**Issue by SpeedmaxX** [m4dhouse/Wireguard-Vpn#2]
Hello, 

great plugin, but when I try to connect to vpn unlimited, I get the following error:

`22:44:54.4513 [InfoBarGenerics] Key 'KEY_OK' (352) Break.
22:44:54.4577 [Network] Removed interface: wg0
22:44:54.4584 [Network] Add new interface: wg0
22:44:54.4608 [OpenWebif] httpserver already started
22:45:01.0053 [DownloadInfo] Error: DownloadInfo server connection failure! (HTTPConnectionPool(host='[www.smart-shell.com](http://www.smart-shell.com/)', port=80): Max retries exceeded with url: /wireguard/version (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnec tion object at 0xadc6c310>, 'Connection to [www.smart-shell.com](http://www.smart-shell.com/)timed out. (connect timeout=3)')))
22:45:01.0055 Error float() argument must be a string or a real number, not 'NoneType'
22:45:01.0056 [eDVBPESReader] ERROR reading PES (fd=65): Function not implemented`

I guess, you are trying to get the current version number from your site. Any Idea how to fix this? The host is accessible from different computers in the lan.

Best regards,
Markus

**Comment by m4dhouse** [comment]
I fixed it, an update soon
