### ISSUE TITLE
Nord VPN - Private key length is incorrect

### ISSUE THREAD

**Issue by skywalker0582** [m4dhouse/Wireguard-Vpn#3]
Hello, 
I'm trying to connect to Nord vpn with an octagon sf8008, latest openATV 7.3 (updated it yesterday) .
The plugin is installed properly so I placed the private key  in the correct file that I located (I used the the token key that I generated  from the Nord VPN dashboard. Its about 65 characters long, and it's the only option because the other option to connect manually is a username and password option) 
But when I go to settings and I press the blue button to load the the private key, it says error, private key length error!!!! 
Am I doing something wrong are there something wrong with the plugin? 
Thank you.

**Comment by m4dhouse** [comment]
Follow this guide to extract NordVpn private key.
https://gist.github.com/bluewalk/7b3db071c488c82c604baf76a42eaad3
The private key is 44 characters long.

**Comment by skywalker0582** [comment]
Thank you :) 
I managed to actually do it
