### ISSUE TITLE
AllowedIP

### ISSUE THREAD

**Issue by Wolframos** [m4dhouse/Wireguard-Vpn#6]
I installed the latest version 6.0 on the VU+ Uno 4k tuner with OpenATV 7.3

It adds the AllowedIP sections to the configuration file, but the application does not take into account the IP addresses contained there 
![putty](https://github.com/m4dhouse/Wireguard-Vpn/assets/3107001/59f93354-04b9-4aa5-9622-4bd356f2d830)

The configuration file is correct, because with these settings the phone connects to the VPN server without any problems:

[Interface]
PrivateKey = key
Address = 10.8.0.10/32
[Peer]
PublicKey = key
AllowedIPs = 192.168.50.0/24,10.8.0.3/32,10.8.0.4/32
Endpoint = IP:51820
PersistentKeepalive = 25

**Comment by m4dhouse** [comment]
In AllowedIps set these addresses:

AllowedIps = 0.0.0.0/1,128.0.0.0/1

**Comment by Wolframos** [comment]
it still does not work.....
![wg](https://github.com/m4dhouse/Wireguard-Vpn/assets/3107001/8f1fbb03-aa16-4cf6-adac-1b554bc5b8cd)

**Comment by m4dhouse** [comment]
Please set in the .conf file 
AllowedIps = 0.0.0.0/1,128.0.0.0/1
Save and reconnect.

<img width="571" alt="Screenshot 2023-11-02 alle 11 26 43" src="https://github.com/m4dhouse/Wireguard-Vpn/assets/35741027/430bb3d2-95ac-4dfd-9175-89159002de2b">

**Comment by Wolframos** [comment]
Please send yours .conf file
I have:
[Interface]
PrivateKey = key
Address = 10.8.0.10/32
[Peer]
PublicKey = key
AllowedIps = 0.0.0.0/1,128.0.0.0/1
Endpoint = IP:51820
PersistentKeepalive = 25

And still not work :(

**Comment by m4dhouse** [comment]
[Interface]
PrivateKey = key
Address = 10.14.0.2/16
DNS = IP

[Peer]
PublicKey = key
AllowedIps = 0.0.0.0/1,128.0.0.0/1
Endpoint = IP:51820
PersistentKeepalive = 25

**Comment by Wolframos** [comment]
ehh, not working :(

allowed ips: (none)

**Comment by Wolframos** [comment]
Do you have also file in /etc/wireguard ???
