### ISSUE TITLE
not working on oatv mipsel box since 7.5

### ISSUE THREAD

**Issue by dazulrich** [m4dhouse/Wireguard-Vpn#8]
ever since you changed from plugin.pyc to plugin.so (v7.5) it stopped working on my mipsel box (ocatgon sf3038) .
no matter which version oatv 7.3 or 7.4 and no matter which python 3.x version. 

the error in the enigma debug log is always the same

`21:16:57.0220 [PluginComponent] Error: Plugin 'Extensions/Wireguard' failed to load!  (/usr/lib/enigma2/python/Plugins/Extensions/Wireguard/plugin.so: cannot open shared object file: No such file or directory)`

redid permissions on the files, nothing. Not clear whether oatv can't load the plugin.so file, or whether the plugin.so is missing a dependency somewhere..

It tried to check with ldd and file to see whether any linked libraries are missing..
Maybe its only compatible with arm boxes?? 

`root@sf3038:/usr/lib/enigma2/python/Plugins/Extensions/Wireguard# ldd plugin.so
        not a dynamic executable
root@sf3038:/usr/lib/enigma2/python/Plugins/Extensions/Wireguard# file plugin.so
plugin.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=e5daf976ddd7eefe1fc8f689c2d05d51def2d79b, not stripped`

**Comment by m4dhouse** [comment]
Sorry, but I don't build for mipsels.

**Comment by dazulrich** [comment]
well, the move to cpython modules is obviously your decision. but maybe u could let the image teams know so they can cater on their feeds. or ensure your own build in updates doesn't offer to update from v7.4 onwards when you are on mipsel... just saying...

**Comment by m4dhouse** [comment]
Please test the Mipsel version (python 3.12 only)
https://github.com/m4dhouse/Wireguard-Vpn/raw/python-3.12/enigma2-plugin-extensions-wireguard-vpn-mips_10.7_all.ipk

**Comment by dazulrich** [comment]
thanks a lot!! ill give it a try asap.

**Comment by dazulrich** [comment]
hi. i have octagon sf3038 with oatv 7.4. installing on top of 7.5 with the linked ipk didnt work. had to uninstall the old v7.5 first. i guess due to name change? fresh install was ok. lots of dependencies installed. 
settings were picked up ok. using nvpn and it seems to be running fine. havent tried bypass yet.
thanks again for compiling for mipsel!

**Comment by nicon12** [comment]
I install on mips open atv 7.3,python 3.11.2 and wireguard dont install

**Comment by m4dhouse** [comment]
> I install on mips open atv 7.3,python 3.11.2 and wireguard dont install

Only python 3.12.x

**Comment by nicon12** [comment]
Ok,but on vu+ uno 4k se it works great on python 3.12.2
